version: '3.0'

services:
  postgres:
    image: postgres
    env_file:
      - ./.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 5432:5432
    container_name: ${DB_DATABASE}-db
